import { getSession } from './storage.js';
import { login, register, logout as authLogout, checkSession } from './auth.js';
import { getWorkouts, addWorkout, updateWorkout, getLastWeightAndReps } from './workouts.js';
import { getMuscleGroups, addMuscleGroup } from './exercises.js';
import { getPlan, savePlan, getBodyMeasures, addBodyMeasure, deleteBodyMeasure } from './body.js';
import { getStatsForExercise } from './stats.js';
import { setUIContext, renderWorkoutsList, updateMuscleGroupsSelect, updateExerciseSelectByMuscle, renderMuscleGroups, renderFavoritesList, populateExerciseSelects } from './ui.js';
import { getPhotoBase64, formatDate, escapeHtml } from './utils.js';

// DOM элементы
const authPage = document.getElementById('authPage');
const appPage = document.getElementById('appPage');
const loginForm = document.getElementById('loginForm');
const registerForm = document.getElementById('registerForm');
const loginTabBtn = document.getElementById('loginTabBtn');
const registerTabBtn = document.getElementById('registerTabBtn');
const doLoginBtn = document.getElementById('doLoginBtn');
const doRegisterBtn = document.getElementById('doRegisterBtn');
const authError = document.getElementById('authError');
const regError = document.getElementById('regError');
const logoutBtn = document.getElementById('logoutBtn');
const currentUserSpan = document.getElementById('currentUser');
const workoutsListDiv = document.getElementById('workoutsList');
const workoutForm = document.getElementById('workoutForm');
const showWorkoutFormBtn = document.getElementById('showWorkoutFormBtn');
const saveWorkoutBtn = document.getElementById('saveWorkoutBtn');
const cancelWorkoutBtn = document.getElementById('cancelWorkoutBtn');
const workoutMuscleGroup = document.getElementById('workoutMuscleGroup');
const workoutExerciseSelect = document.getElementById('workoutExerciseSelect');
const workoutDate = document.getElementById('workoutDate');
const setsContainer = document.getElementById('setsContainer');
const addSetBtn = document.getElementById('addSetBtn');
const workoutPhoto = document.getElementById('workoutPhoto');
const photoPreview = document.getElementById('photoPreview');
const workoutError = document.getElementById('workoutError');
const statsExerciseSelect = document.getElementById('statsExerciseSelect');
const periodBtns = document.querySelectorAll('.period-stats-btn');
const statsChartCanvas = document.getElementById('statsChart');
const statsNumbers = document.getElementById('statsNumbers');
const musclesContainer = document.getElementById('musclesContainer');
const addGroupBtn = document.getElementById('addGroupBtn');
const newGroupName = document.getElementById('newGroupName');
const favoritesList = document.getElementById('favoritesList');
const weekPlanContainer = document.getElementById('weekPlanContainer');
const editPlanBtn = document.getElementById('editPlanBtn');
const planEditor = document.getElementById('planEditor');
const planDaysEditor = document.getElementById('planDaysEditor');
const savePlanBtn = document.getElementById('savePlanBtn');
const cancelPlanBtn = document.getElementById('cancelPlanBtn');
const addMeasureBtn = document.getElementById('addMeasureBtn');
const measureForm = document.getElementById('measureForm');
const saveMeasureBtn = document.getElementById('saveMeasureBtn');
const cancelMeasureBtn = document.getElementById('cancelMeasureBtn');
const measuresHistory = document.getElementById('measuresHistory');
const measureDate = document.getElementById('measureDate');
const measureChest = document.getElementById('measureChest');
const measureBicepsL = document.getElementById('measureBicepsL');
const measureBicepsR = document.getElementById('measureBicepsR');
const measureWaist = document.getElementById('measureWaist');
const measureThighL = document.getElementById('measureThighL');
const measureThighR = document.getElementById('measureThighR');

let currentUser = null;
let currentEditIndex = null;
let statsChart = null;
let currentPeriod = 'week';

const tabs = document.querySelector
